### PR TITLE
provide ability to create client from env vars

### PR DESCRIPTION
**Pull request by mdb**
This is a quick pass at addressing issue #65.

@mitruly You mention that "A combination of `EnvironmentVariableCredentialsProvider` for AWS credentials and `System.env` can be used to implement this." If what I've done isn't what you have in mind, could you elaborate a bit?

### CODE REVIEW

**Comment by mitruly** [comment]
@mdb Yes, this is the direction that we were thinking.

Does `System.getenv()` work properly for you with the client? I published this to local (using `mvn install`) and created a project to import:

```
public class Test {
    public static void main(String[] args) {

        System.out.println("API URL: " + System.getenv("VINYLDNS_API_URL"));
        System.out.println("Access key: " + System.getenv("VINYLDNS_ACCESS_KEY"));
        System.out.println("Secret key: " + System.getenv("VINYLDNS_SECRET_ACCESS_KEY"));
        VinylDNSClient client = new VinylDNSClientImpl();

        VinylDNSResponse<ListZonesResponse> listZonesResponse = client.listZones(new ListZonesRequest());
    }
}
```

I run into an error within the `BasicAWSCredentials` even though the environment variables are defined:
```
API URL: http://localhost:9000
Access key: testUserAccessKey
Secret key: testUserSecretKey
Exception in thread "main" java.lang.IllegalArgumentException: Access key cannot be null.
	at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
	at io.vinyldns.java.VinylDNSClientImpl.<init>(VinylDNSClientImpl.java:57)
	at HelloWorld.main(Test.java:21)
```

**Comment by mdb** [comment]
@mitruly Interesting. And am I correct in thinking the `System.out.println` lines print out the expected nonempty strings?

**Comment by mitruly** [comment]
@mdb Yes, those are print statements from my run; however, I just realized that I was using `VINYLDNS_ACCESS_KEY` instead of `VINYLDNS_ACCESS_KEY_ID`, heh.

Testing this out correctly, it appears to work as intended. Would you be able to add some update information to the `README.md` for the environment variables?

**Comment by mdb** [comment]
@mitruly I've added some `README` explanation. Are there any other changes you'd like to see?

**Comment by mitruly** [comment]
@mdb Nope - this PR is good to go. Thanks again for this contribution!!

**Pull request merged**
